apiVersion: v2
name: k8sscrmgr
description: Install Kubernetes SCR Manager
typetype: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/helm/helm/main/docs/img/helm-icon.svg