# values.yaml
installName: ""

# default scr namepsace
defaultScrNamespace: scr

# k8s-scr-mgr parameters
k8sScrMgr:
  host:
  kubeconfig:
  scr_yaml_template:
  viyaNamespace: viya
  container_prefix: scr
  mas_pod: sas-microanalytic-score
  list_scr: True
  pull_scr: True
  restart_scr: True
  delete_scr: True
  getlog_scr: True
  getlog_mas: True 

# List of scr parameters used when creating more than one SCR namespace
scr:
  - publishingDestination: ''
    namespace: ''
    dbCredentials: ''
    setDbSecret: False
    dockerCredentials:
      baseRepoURL: ''
      registryId: ''
      registryPassword: ''